# Generated by Django 6.0.5 on 2026-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_memo',
            field=models.TextField(blank=True, default='', verbose_name='スタッフメモ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='channel',
            field=models.CharField(choices=[('web', 'Web予約'), ('phone', '電話予約'), ('hotpepper', 'ホットペッパー'), ('tabelog', '食べログ'), ('gate', 'GATE（イデアレコード）'), ('walk', '飛び込み'), ('staff', 'スタッフ直接入力')], default='web', max_length=20, verbose_name='予約経路'),
        ),
    ]
