# Generated by Django 6.0.5 on 2026-05-08 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='席コード')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='定員（人）')),
                ('can_merge', models.BooleanField(default=False, help_text='掘り炬燵など複数ブロックを結合できる席に True を設定', verbose_name='連結可能')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '席',
                'verbose_name_plural': '席',
                'ordering': ['section__sort_order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='予約者名')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('party_size', models.PositiveSmallIntegerField(verbose_name='人数')),
                ('start_at', models.DateTimeField(verbose_name='来店日時')),
                ('end_at', models.DateTimeField(help_text='AIが滞在時間と次の予約の重複を判定するために使用', verbose_name='退席予定日時')),
                ('status', models.CharField(choices=[('pending', '仮予約（未確認）'), ('confirmed', '確定'), ('seated', '着席中'), ('completed', '会計済み'), ('cancelled', 'キャンセル'), ('no_show', '無断キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('channel', models.CharField(choices=[('web', 'Web予約'), ('phone', '電話予約'), ('walk', '飛び込み'), ('staff', 'スタッフ直接入力')], default='web', max_length=20, verbose_name='予約経路')),
                ('notes', models.TextField(blank=True, verbose_name='備考・要望')),
                ('ai_check_result', models.JSONField(blank=True, help_text='Claude APIによる重複チェック結果をJSON形式で保存', null=True, verbose_name='AI判定ログ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='複数席のうち代表となる席（フロアマップ表示用）', verbose_name='主席フラグ')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_seats', to='reservations.reservation', verbose_name='予約')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_seats', to='reservations.seat', verbose_name='席')),
            ],
            options={
                'verbose_name': '予約席',
                'verbose_name_plural': '予約席',
            },
        ),
        migrations.CreateModel(
            name='SeatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='備考')),
                ('seat_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='reservations.seat', verbose_name='席A')),
                ('seat_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='reservations.seat', verbose_name='席B')),
            ],
            options={
                'verbose_name': '席連結設定',
                'verbose_name_plural': '席連結設定',
            },
        ),
        migrations.CreateModel(
            name='SeatSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='セクション名')),
                ('section_type', models.CharField(choices=[('counter', 'カウンター'), ('table', 'テーブル'), ('kotatsu', '掘り炬燵')], max_length=20, verbose_name='席タイプ')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='表示順')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_sections', to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '席セクション',
                'verbose_name_plural': '席セクション',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='reservations.seatsection', verbose_name='セクション'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('label', models.CharField(blank=True, help_text='例: ディナー早め / ラストオーダー後 など', max_length=20, verbose_name='表示ラベル')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '予約枠',
                'verbose_name_plural': '予約枠',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['store', 'start_at'], name='reservation_store_i_6ced34_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['store', 'status'], name='reservation_store_i_c96bdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationseat',
            unique_together={('reservation', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='seatlink',
            unique_together={('seat_a', 'seat_b')},
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('section', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('store', 'start_time')},
        ),
    ]
