# Generated by Django 6.0.5 on 2026-05-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('staff', 'スタッフ'), ('manager', '店長'), ('owner', 'オーナー'), ('chief_administrator', '最高管理者'), ('administrator', '管理人')], default='staff', max_length=20, verbose_name='役割'),
        ),
    ]
