# Generated by Django 6.0.5 on 2026-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='エリア（例：徳島市）'),
        ),
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='営業時間（例：17:00〜24:00）'),
        ),
        migrations.AddField(
            model_name='store',
            name='closed_day',
            field=models.CharField(blank=True, max_length=100, verbose_name='定休日（例：月曜日）'),
        ),
        migrations.AddField(
            model_name='store',
            name='genre',
            field=models.CharField(blank=True, max_length=50, verbose_name='ジャンル（例：居酒屋）'),
        ),
        migrations.AddField(
            model_name='store',
            name='reservation_url',
            field=models.URLField(blank=True, verbose_name='予約URL'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_color',
            field=models.CharField(default='#2d6a4f', max_length=7, verbose_name='イメージカラー（例：#c9a84c）'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='テキストカラー（例：#c9a84c）'),
        ),
    ]
