# Generated by Django 6.0.5 on 2026-05-15 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('reservations', '0002_reservation_staff_memo_alter_reservation_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='グループID'),
        ),
        migrations.AddField(
            model_name='order',
            name='seat_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='席コード'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation'),
        ),
    ]
