# Generated by Django 6.0.5 on 2026-05-17 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_rename_is_active_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='accounts.store', verbose_name='店舗'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.store', verbose_name='店舗'),
        ),
    ]
