# Generated by Django 6.0.5 on 2026-05-18 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store_area_store_business_hours_store_closed_day_and_more'),
        ('orders', '0003_menucategory_store_order_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='お名前')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.TextField(verbose_name='住所')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200, verbose_name='Stripe PaymentIntent ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='決済済み')),
                ('status', models.CharField(choices=[('pending', '未確認'), ('confirmed', '確認済み'), ('shipped', '発送済み')], default='pending', max_length=10, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注文日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_orders', to='accounts.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '直売注文',
                'verbose_name_plural': '直売注文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProduceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.menuitem', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_items', to='orders.produceorder', verbose_name='注文')),
            ],
            options={
                'verbose_name': '直売注文明細',
                'verbose_name_plural': '直売注文明細',
            },
        ),
    ]
