# Generated by Django 6.0.5 on 2026-05-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_produceorder_produceorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='badge',
            field=models.CharField(blank=True, max_length=20, verbose_name='バッジ（例：人気No.1）'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(default='房', max_length=10, verbose_name='単位（例：房・袋）'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='payment_method',
            field=models.CharField(default='cash', max_length=10, verbose_name='支払方法'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='来店予定日'),
        ),
        migrations.AlterField(
            model_name='produceorder',
            name='address',
            field=models.TextField(blank=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='produceorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='produceorder',
            name='status',
            field=models.CharField(choices=[('pending', '未確認'), ('confirmed', '確認済み・OK'), ('rejected', 'お断り'), ('shipped', '発送済み')], default='pending', max_length=10, verbose_name='ステータス'),
        ),
    ]
