# Generated by Django 6.0.5 on 2026-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menuitem_badge_menuitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='画像URL（Cloudinary）'),
        ),
    ]
