# Generated by Django 6.0.5 on 2026-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_menuitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='希望配送日'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='order_type',
            field=models.CharField(choices=[('visit', '来店受取'), ('delivery', '配送（贈答）')], default='visit', max_length=10, verbose_name='注文種別'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='届け先氏名'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='届け先電話番号'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='sender_address',
            field=models.TextField(blank=True, verbose_name='送り主住所'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='送り主氏名'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='送り主電話番号'),
        ),
        migrations.AddField(
            model_name='produceorder',
            name='sender_postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='送り主郵便番号'),
        ),
    ]
