# Generated by Django 6.0.5 on 2026-05-20 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_produceorder_delivery_date_produceorder_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1, verbose_name='届け先番号')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='届け先氏名')),
                ('receiver_phone', models.CharField(blank=True, max_length=20, verbose_name='届け先電話番号')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address', models.TextField(verbose_name='住所')),
                ('note', models.TextField(blank=True, verbose_name='個別備考')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='orders.produceorder', verbose_name='注文')),
            ],
            options={
                'verbose_name': '届け先',
                'verbose_name_plural': '届け先',
                'ordering': ['index'],
            },
        ),
    ]
