# Generated by Django 6.0.5 on 2026-05-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='box_count',
            field=models.PositiveIntegerField(default=1, verbose_name='箱数'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='box_size',
            field=models.PositiveIntegerField(choices=[(1, '1kg箱'), (2, '2kg箱'), (5, '5kg箱')], default=2, verbose_name='箱サイズ（kg）'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='希望配送日'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='note',
            field=models.TextField(blank=True, verbose_name='個別備考（のし・比率など）'),
        ),
        migrations.CreateModel(
            name='DeliveryAddressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.deliveryaddress', verbose_name='届け先')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.menuitem', verbose_name='品種')),
            ],
            options={
                'verbose_name': '品種選択',
                'verbose_name_plural': '品種選択',
            },
        ),
    ]
